config/routes.rb
Rails.application.routes.draw do

  resources :products do
    patch :decrement_and_show_message, on: :member
    patch :decrement_as_admin, on: :member
    patch :add_quantity, on: :member
    patch :give, on: :member
    patch :destroy_borrowed, on: :member
  end

  get "rental/successful", to: "rental#successful"
  post 'password/check', to: 'products#check_password'

  resources :rental, only:[:index, :show, :successful]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rental#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/items_borrowed.rb
class ItemsBorrowed < ApplicationRecord
end

app/models/number.rb
class Number < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
    @borrowed = ItemsBorrowed.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def decrement_and_show_message
    @product = Product.find(params[:id])
    if @product.quantity > 0
      @product.update(quantity: @product.quantity - 1)
      @product.update(borrowed: @product.borrowed + 1)

      old_number=Number.find_by(id:1).numer
      Number.find_by(id:1).update(numer:old_number + 1 )

      number=Number.find_by(id:1).numer
      name=@product.title
      data=@product.updated_at
      given=false
      @borrowed = ItemsBorrowed.new(numer: number, title: name, date: data, given: given)

      respond_to do |format|
        format.json { render json: { message: "Successful rental", quantity: @product.quantity } }
        format.html { redirect_to rental_successful_path }
        @borrowed.save
      end
    else
      respond_to do |format|
        format.json { render json: { message: "Out of stock. Cannot rent." } }
      end
    end
  end

  def decrement_as_admin
    @product = Product.find(params[:id])
    @product.update(quantity: @product.quantity - 1)
    @product.update(borrowed: @product.borrowed + 1)
    respond_to do |format|
      format.json { render json: { message: "Successful", quantity: @product.quantity } }
      format.json { render json: { message: "Successful", borrowed: @product.borrowed } }
    end
  end

  def add_quantity
    @product = Product.find(params[:id])
    @product.update(quantity: @product.quantity + 1)
    @product.update(borrowed: @product.borrowed - 1)
    respond_to do |format|
      format.json { render json: { message: "Successful", quantity: @product.quantity } }
      format.json { render json: { message: "Successful", borrowed: @product.borrowed } }
    end
  end


  def check_password
    if params[:password] == 'haslo'
      redirect_to products_path, alert: "Hasło poprawne"
    else
    end
  end

  def give
    @borrowed = ItemsBorrowed.find(params[:id])
    @borrowed.update(given: true )
    respond_to do |format|
      format.json { render json: { message: "Successful", given: @borrowed.given } }
    end
  end

  def destroy_borrowed
    @borrowed = ItemsBorrowed.find(params[:id])
    @product = Product.find_by(title: @borrowed.title)
    @product.update(quantity: @product.quantity + 1)
    @product.update(borrowed: @product.borrowed - 1)
    @borrowed.destroy

    respond_to do |format|
      format.json { render json: { message: "Successful"} }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price, :quantity, :borrowed)
    end


end

app/controllers/rental_controller.rb
class RentalController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def successful

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rental_helper.rb
module RentalHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardsAndSkates</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <h1 style="background-color: midnightblue; margin:-16px -8px 30px -10px; color: white; padding: 40px 20px 20px 20px; text-align:left;" >WYPOŻYCZALNIA SPRZĘTU "SNOW"</h1>
  <%= link_to image_tag("house.svg"), root_path, title: "Strona Główna" , class: "House_button button-without-border-and-background" %>
  <%#= link_to image_tag("house.svg"), products_path, title: "Strona Główna" , class: "Admin_button" %>

  <form action="/password/check" class="Admin_login_button" method="post" id="password_form">
    <input style="height: 30px; width: 200px; border: none" type="password" name="password">
    <input class="login_button" type="submit" value="Zaloguj na konto Administratora">
  </form>

  <body style="background: url('<%= asset_path "back.jpg" %>') no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;">
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<style>
    table{
        margin: 0 auto;
        width: 60%;
        font-size: 30px;
        border-radius: 20px;
    }
    .description_item
    {
        text-align: left;
        padding-left: 100px;
        color: midnightblue;
    }
    .field{
        height: 40px;
        padding-left: 10px;
        width: 500px;
        font-size: 25px;
        text-decoration: none;
        border-radius: 5px; /*up to date browsers support this, but you can add prefixes if you want*/

        border: 0;
    }
</style>
<div style="background-color: rgba(144, 144, 144, 0.85);
  border-radius: 15px;">
  <%= form_with(model: product) do |form| %>
    <% if product.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <table>
      <tr>
        <td class="description_item"> Nazwa wypożyczanego przedmiotu</td>
        <td style="text-align: center; padding: 15px 150px 15px 15px; "><%= form.text_field :title, class: "field"%></td>
      </tr>
      <tr>
        <td class="description_item">Cena za wypożyczenie za dobę</td>
        <td style="text-align: center; padding: 15px 150px 15px 15px; "><%= form.text_field :price, class: "field" %></td>
      </tr>
      <tr>
        <td class="description_item">Dostępna ilość</td>
        <td style="text-align: center; padding: 15px 150px 15px 15px; "><%= form.number_field :quantity, class: "field" %></td>
      </tr>
      <tr>
        <td class="description_item">Ilość Wypożyczonych</td>
        <td style="text-align: center; padding: 15px 150px 15px 15px; ">
          <% value = form.object.borrowed.nil? ? 0 : form.object.borrowed %>
          <%= form.number_field :borrowed, value: value, readonly: true, class: "field" %>
        </td>
      </tr>
    </table>
    <div style="margin: 0 auto; width: 80%; align-items: center; display: flex; justify-content: center;">
      <button type="submit" style="align-items: center" class="button-without-border-and-background"><%= image_tag "check-circle.svg" %></button>
    </div>

  <% end %>

</div>

app/views/products/_product.html.erb
<style>
  table{
      margin: 0 auto;
      width: 60%;
      background-color: rgba(144, 144, 144, 0.85);
      font-size: 30px;
      border-radius: 20px;
  }
  .description_item
  {
      text-align: left;
      padding-left: 100px;
      color: midnightblue;
  }
</style>
<div style="margin: 100px;">
  <table id="<%= dom_id product %>">
    <tr>
      <td class="description_item"> Nazwa wypożyczanego przedmiotu</td>
      <td style="text-align: center; padding: 15px 150px 15px 15px; "><%= product.title %></td>
    </tr>
    <tr>
      <td class="description_item">Cena za wypożyczenie za dobę</td>
      <td style="text-align: center;  padding: 15px 150px 15px 15px"><%= product.price %> zł</td>
    </tr>
    <tr>
      <td class="description_item">Dostępna ilość</td>
      <td style="text-align: center;  padding: 15px 150px 15px 15px"><%= product.quantity%></td>
    </tr>
    <tr>
      <td class="description_item">Ilość Wypożyczonych</td>
      <td style="text-align: center;  padding: 15px 150px 15px 15px"><%= product.borrowed%></td>
    </tr>
  </table>

</div>

app/views/products/edit.html.erb
<h1 style="margin: 0 auto; width: 80%; font-size: 40px; align-items: center; text-align: center; margin-bottom: 50px;">EDYTOWANIE PRODUKTU</h1>

<%= render "form", product: @product %>

<br>

<div  style="margin: 0 auto; width: 80%; align-items: center; display: flex; justify-content: center; ">
  <div style="padding: 10px"><%= link_to image_tag("show_icon.svg"), @product, title: "Pokaż produkt", class: "button-without-border-and-background" %></div>
  <div style="padding: 10px"><%= link_to image_tag("arrow-left-circle.svg"), products_path ,title:"Wróć do Listy produktów" , class: "button-without-border-and-background" %></div>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<style>
    table {
        margin: 0 auto;
        width: 80%;
        text-align: center;
        padding: 10px;
        background-color: rgba(144, 144, 144, 0.85);
        border-radius: 15px;
    }
    td{
        font-size: 20px;
    }
    .item:hover{
        background-color: #666666;
    }
    .add{
        margin: 0 auto;
        width: 40%;
        background-color: midnightblue;
        padding: 20px;
        font-size: 30px;
        border-radius: 20px;
        margin-top: 50px;
        color: white;
        text-align: center;
    }
    .add:hover{
        transform: scale(1.05);
        cursor: pointer;
        background-color: #2E2F30;
    }
</style>


<div id="products">
  <table border="1">
    <tr>
      <td style="padding: 15px"><strong>NAZWA PRODUKTU:</strong></td>
      <td style="padding: 15px"><strong>CENA:</strong></td>
      <td style="width: 200px" ><strong>DOSTĘPNA ILOŚĆ:</strong></td>
      <td style="width: 200px" ><strong>ILOŚĆ WYPOŻYCZONYCH:</strong></td>
    </tr>
    <% @products.each do |product| %>
      <tr class="item">
        <td style="padding: 15px"><%= product.title %></td>
        <td style="padding: 15px"><%= product.price %> zł</td>
        <td style="padding: 15px"><%= product.quantity %></td>
        <td style="padding: 15px"><%= product.borrowed %></td>

        <td>
          <div style="display: flex; justify-content: space-around ">
            <div style="padding: 10px"><%= link_to image_tag("show_icon.svg"), product, title: "Pokaż produkt", class: "button-without-border-and-background" %></div>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<div class="add" onclick="location.href='<%= new_product_path %>';">
  Dodaj nowy produkt
</div>

<table border="1" style="margin-top: 40px">
  <tr>
    <td style="padding: 15px"><strong>NAZWA PRODUKTU:</strong></td>
    <td style="padding: 15px"><strong>DATA I GODZINA WYPOŻYCZENIA:</strong></td>
    <td style="width: 200px" ><strong>NUMER ZAMÓWNIENIA:</strong></td>
    <td style="width: 200px" ><strong>WYDANE:</strong></td>
  </tr>
  <% @borrowed.each do |borrowed| %>
    <tr class="item">
      <td style="padding: 15px"><%= borrowed.title %></td>
      <td style="padding: 15px"><%= borrowed.date %></td>
      <td style="padding: 15px"><%= borrowed.numer %></td>
      <td style="padding: 15px">
        <% if borrowed.given==false %>
          <%= button_to image_tag("clipboard2-check.svg"), give_product_path(borrowed), method: :patch , title: "Wydaj Produkt", class: "button-without-border-and-background" %>
        <% else %>
          <%= "Już wydane" %>
        <% end %>
        </td>
      <td style="padding: 15px">
        <%= button_to image_tag("reply.svg"), destroy_borrowed_product_path(borrowed), method: :patch, title: "Zwróć produkt", class: "button-without-border-and-background" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h1 style="margin: 0 auto; width: 80%; font-size: 40px; align-items: center; text-align: center; margin-bottom: 50px;">DODAJ NOWY PRODUKT</h1>

<%= render "form", product: @product %>

<br>

<div style="margin: 0 auto; width: 80%; align-items: center; display: flex; justify-content: center;">
  <div style="padding: 10px"><%= link_to image_tag("arrow-left-circle.svg"), products_path ,title:"Wróć do Listy produktów" , class: "button-without-border-and-background" %></div>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div  style="margin: 0 auto; width: 80%; align-items: center; display: flex; justify-content: center;">
  <div style="padding: 10px"><%= link_to image_tag("arrow-left-circle.svg"), products_path ,title:"Wróć do Listy produktów" , class: "button-without-border-and-background" %></div>
  <div style="padding: 10px"><%= link_to image_tag("gear.svg"), edit_product_path(@product) ,title: "Edytuj ten produkt", class: "button-without-border-and-background" %> </div>
  <div style="padding: 8px 4px"><%= button_to image_tag("trash.svg"), @product, method: :delete, title: "Usuń ten Produkt z Listy", class: "button-without-border-and-background" %></div>
</div>

app/views/rental/index.html.erb
<p style="color: green"><%= notice %></p>

<style>
    table {
        margin: 0 auto;
        width: 80%;
        text-align: center;
        padding: 10px;
        background-color: rgba(144, 144, 144, 0.85);
        border-radius: 15px;
    }
    td{
        font-size: 20px;
    }
    .item:hover{
        background-color: #666666;
    }
</style>

<div id="products">
  <table border="1">
    <tr>
      <td style="padding: 15px"><strong>NAZWA PRODUKTU:</strong></td>
      <td style="padding: 15px"><strong>CENA:</strong></td>
      <td style="width: 150px;" ><strong>DOSTĘPNA <br> ILOŚĆ:</strong></td>
    </tr>
    <% @products.each do |product| %>
      <tr class="item">
        <td style="padding: 15px"><%= product.title %></td>
        <td style="padding: 15px"><%= product.price %> zł</td>
        <td style="padding: 15px"><%= product.quantity %></td>
        <td>
        <p>
          <%= link_to image_tag("show_icon.svg"), rental_path(product), title: "Pokaż produkt", class: "button-without-border-and-background" %>

        </p>
      </td>
    </tr>
  <% end %>
  </table>
</div>

app/views/rental/show.html.erb
<p style="color: green"><%= notice %></p>


<%= render @product %>

<div style="margin: 0 auto; width: 80%; align-items: center; display: flex; justify-content: center;">
  <div style="padding: 10px"><%= link_to image_tag("arrow-left-circle.svg"), root_path, title: "Wróć do Listy Produktów", class: "button-without-border-and-background" %></div>
  <div style=" padding: 10px">
    <% if @product.quantity > 0 %>
      <%= button_to image_tag("check-circle.svg"), decrement_and_show_message_product_path(@product), method: :patch, title: "Wypożycz ten przedmiot", class: "button-without-border-and-background" %>
    <% else %>
      <%= "Artukuł niedostępny." %>
      <br>
      <%= "Ilość wyczerpana" %>
    <% end %>

  </div>
</div>

app/views/rental/successful.html.erb
<p style="color: green"><%= notice %></p>

<div class="center-text ">
  <div class="success" >UDANE WYPOŻYCZENIE!</div>
  <div style=" width: 500px; margin-top: 20px; font-size: 30px; text-align: center " >
    Udaj się do stoiska pracownika aby odebrać Przedmiot. <br>
    Numer twojego zamówienia to: <p style="text-align: center" class="success" ><%=Number.find_by(id:1).numer %></p>
  </div>

  <div style="padding: 10px"><%= link_to image_tag("arrow-left-circle.svg"), root_path, title: "Wróć do Listy Produktów", class: "button-without-border-and-background" %></div>
</div>

<style>
    .center-text {
        text-align: center;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: rgba(144, 144, 144, 0.85);
        border-radius: 15px;
        padding: 30px;
    }
    .success
    {
        font-size: 40px;
        color: green;
    }

</style>